name: resize_media
description: Resize media files to a specified size
version: 1.0.0
homepage: "https://github.com/tapeo/resize_media"
repository: "https://github.com/tapeo/resize_media"

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      # android:
      #   package: it.matteoricupero.resize_media
      #   pluginClass: ResizeMediaPlugin
      ios:
        pluginClass: ResizeMediaPlugin
